### ISSUE TITLE
addInterceptors for endpoint selectively

### ISSUE THREAD

**Issue by MaskeZen** [marschall/spring-ws-example#1]
Hello Philippe Marschall, may be you know how to addInterceptors for one endpoint but not for others, I need secure one but make free to use others, thanks for any help.

**Comment by marschall** [comment]
Hello Diego

I do not. I believe the right place would be the spring-ws tag on Stackoverflow https://stackoverflow.com/questions/tagged/spring-ws

Cheers
Philippe

**Comment by MaskeZen** [comment]
Yes, this is right.
Thanks Philippe.
